<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [ProgrammaticallyRunningSuite]">
  <test thread-count="5" name="test1(failed)">
    <classes>
      <class name="testsuite.Test_Cacultor">
        <methods>
          <include name="afterSuite"/>
          <include name="test_minus" invocation-numbers="0 1"/>
          <include name="afterMethod"/>
          <include name="beforeTest"/>
          <include name="afterClass"/>
          <include name="test_add" invocation-numbers="0 1"/>
          <include name="afterTest"/>
          <include name="beforeSuite"/>
          <include name="beforeMethod"/>
          <include name="beforeClass"/>
        </methods>
      </class> <!-- testsuite.Test_Cacultor -->
      <class name="package_test_2.Test_Cry">
        <methods>
          <include name="beforeMethod"/>
          <include name="test_cry1" invocation-numbers="0 1"/>
          <include name="beforeClass"/>
          <include name="test_cry2" invocation-numbers="0 1"/>
          <include name="beforeTest"/>
          <include name="afterMethod"/>
          <include name="afterSuite"/>
          <include name="afterTest"/>
          <include name="testSingleString"/>
          <include name="afterClass"/>
          <include name="beforeSuite"/>
        </methods>
      </class> <!-- package_test_2.Test_Cry -->
    </classes>
  </test> <!-- test1(failed) -->
</suite> <!-- Failed suite [ProgrammaticallyRunningSuite] -->
